# Generated by Django 5.1.7 on 2025-03-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('severity', models.CharField(max_length=10)),
                ('fixed', models.BooleanField(default=False)),
            ],
        ),
    ]
